## Correct Target
Simulation of environment under the correct syndrome extraction circuits in order to find out if target state is correct

In [1]:
import numpy as np

import sys

sys.path.append(r'../')
from rlftqc.simulators.clifford_gates import CliffordGates

%load_ext autoreload
%autoreload 2
%matplotlib inline

from rlftqc.envs.logical_state_preparation_env import LogicalStatePreparationEnv
from rlftqc.envs.wrappers.tableau_to_grid_wrapper import TableauToGridWrapper
from rlftqc.envs.cells import build_cells, get_mapping, get_target
from rlftqc.logical_state_preparation import LogicalStatePreparation

target = get_target()

print(f"len(target): {len(target)}")

cliff_gates = CliffordGates(17)

cells_from_helper = build_cells()
mapping = get_mapping()
action_mask = np.zeros((len(cells_from_helper), 5), dtype=int)
for i, cell in enumerate(cells_from_helper):
    action_mask[i, :] = np.array(cell.action_mask)


gates = [cliff_gates.h, cliff_gates.cx]
lsp = LogicalStatePreparation(target, gates=gates, cells=cells_from_helper, action_mask=action_mask, mapping=mapping)




[[0 1]
 [0 2]
 [1 1]
 [1 2]
 [1 3]
 [1 4]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [2 4]
 [3 0]
 [3 1]
 [3 2]
 [3 3]
 [4 2]
 [4 3]]
index_grid:
 [[-1  0  1 -1 -1]
 [-1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 -1]
 [-1 -1 15 16 -1]]
mapping: [[0 1]
 [0 2]
 [1 1]
 [1 2]
 [1 3]
 [1 4]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [2 4]
 [3 0]
 [3 1]
 [3 2]
 [3 3]
 [4 2]
 [4 3]]
target_cells: [Cell(cell_type='bulk', measure_qubit=3, data_qubits=Neighbors(north=1, east=4, south=8, west=2), action_mask=(True, True, True, True, True)), Cell(cell_type='bulk', measure_qubit=7, data_qubits=Neighbors(north=2, east=8, south=12, west=6), action_mask=(True, True, True, True, True)), Cell(cell_type='bulk', measure_qubit=9, data_qubits=Neighbors(north=4, east=10, south=14, west=8), action_mask=(True, True, True, True, True)), Cell(cell_type='bulk', measure_qubit=13, data_qubits=Neighbors(north=8, east=14, south=15, west=12), action_mask=(True, True, True, True, True)), Cell(cell_type='boundary', measure_qubit=0, data_qubits=N

/Users/shakeeb/dev/rlftqc-biased-noise/.rlftqc-venv/lib/python3.12/site-packages/jax/_src/ops/scatter.py:108: FutureWarning: scatter inputs have incompatible types: cannot safely cast value from dtype=int32 to dtype=uint8 with jax_numpy_dtype_promotion='standard'. In future JAX releases this will result in an error.
  warnings.warn(


17
h operator: [[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
17
h operator: [[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
17
h operator: [[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
17
h operator: [[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
17
h operator: [[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
17
h operator: [[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
17
h operator: [[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
17
h operator: [[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [

In [ ]:
env = lsp.env

for i, cell in enumerate(cells_from_helper):
    if cell.cell_type == 'bulk':
        print(f"Bulk Cell {i}: {cell}")
        # 
    else:
        print(f"Boundary Cell {i}: {cell}")
    


Bulk Cell 0: Cell(cell_type='bulk', measure_qubit=3, data_qubits=Neighbors(north=1, east=4, south=8, west=2), action_mask=(True, True, True, True, True))
Bulk Cell 1: Cell(cell_type='bulk', measure_qubit=7, data_qubits=Neighbors(north=2, east=8, south=12, west=6), action_mask=(True, True, True, True, True))
Bulk Cell 2: Cell(cell_type='bulk', measure_qubit=9, data_qubits=Neighbors(north=4, east=10, south=14, west=8), action_mask=(True, True, True, True, True))
Bulk Cell 3: Cell(cell_type='bulk', measure_qubit=13, data_qubits=Neighbors(north=8, east=14, south=15, west=12), action_mask=(True, True, True, True, True))
Boundary Cell 4: Cell(cell_type='boundary', measure_qubit=0, data_qubits=Neighbors(north=None, east=1, south=2, west=None), action_mask=(True, False, True, True, False))
Boundary Cell 5: Cell(cell_type='boundary', measure_qubit=5, data_qubits=Neighbors(north=None, east=None, south=10, west=4), action_mask=(True, False, False, True, True))
Boundary Cell 6: Cell(cell_type='bou